### ISSUE TITLE
Additional device IDs

### ISSUE THREAD

**Issue by BastianZim** [ruebox/openhab2-addons#2]
Hi, so I extracted the whole device part from the getAll.xml file and uploaded it below. Not sure if I cut out the correct part, so maybe have a look at it if it's correct or not. 
My installation is in German, so if you need anything translated, please do not hesitate to contact me.
Thanks for developing this, and if you need anything shoot me a message.
Best.

Short question, if I find bugs, would you prefer me opening them up here, or writing them to you on OpenHAB?
[device type.xml.zip](https://github.com/ruebox/openhab2-addons/files/1810923/device.type.xml.zip)

**Comment by ruebox** [comment]
Support for binary switch and thermostat added. 
Tests pending

**Comment by BastianZim** [comment]
Tested with the following results:

1. Light-groups are being discovered just like raffstore-actor-groups but do not "talk back". If a light is on, it is not shown. That was not something specifically in your update but I just wanted to inform you.
2. Thermostats aren't being discovered
4. Switches with 8 channels are being discovered but nothing happens. I mapped each switch to a light in the B+J platform but if I turn them on in Openhab, nothing happens. Could be the case since I only mapped them in B+J, should I try Openhab as well?
5. If you want to add other switches as well, I have 1/1, 2/2 and 1/1 motion sensor as well which should all be in the file, otherwise please just send me a message and I'll try to find them.

**Comment by ruebox** [comment]
Hi,
thanks for the feedback. Regarding

1. Yes, there is no talk back, yet. _Are the light groups working?_
2. I implemented the deviceTypeId=9004 for thermostats. Could be that you have another id. If generated a new jar that will encode the deviceTypeID within the caption of the thing. It would be great if you could test this with "DummyItems" enabled and provide me the names of some sample thermostats.
3. Same as 2. and could you please provide me the openhab.log. Thanks. 
4. When the other stuff is working ... why not ;-)
[org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.zip](https://github.com/ruebox/openhab2-addons/files/1823019/org.openhab.binding.freeathome-2.0.0-SNAPSHOT.jar.zip)

**Comment by BastianZim** [comment]
Hi, no problem, thank you for developing the binding.

1. Yes, the lights are working, but as expected only in a group
2. Tried that, but as soon as I switched on dummies, everything went offline, and Openhab couldn't connect to anything anymore. _Edit. A simple reboot fixed that but now the dummy switch is off again. I'll reinstall it and try again. Should I create a different issue for that?_
3. Will do, as soon as I get it up and running again.
4. Ok, sounds great, thanks!

**Comment by ruebox** [comment]
Hi, great.

Regarding switches. You could change the id of the data point from idp0000 -> odp0000 or incrementing it from idp0000 -> idp0001 ... Perhaps there will be a reaction. 

But I do not know what happens with the device :-)

**Comment by BastianZim** [comment]
Ok, let me try that later. 

~~I installed it again and there is no dummy switch anymore, is that correct? I downloaded it from [here](https://github.com/ruebox/openhab2-addons/releases/tag/v1.0.1-alpha3). 
What's strange is, is that the light groups are now shown as a dummy again, is that expected?
I installed the wrong version, right? Strange, I went with your latest download link, give me a sec, I'll reinstall it.~~

Was the wrong version, sorry, dummies are working and I'll try everything now.

**Comment by BastianZim** [comment]
New problem, sorry for spamming your inbox.

Dummy channels are not shown under the "control" section of the Paper UI and the other channels are only show once I add at least one.

**Comment by BastianZim** [comment]
Tried changing the data point but nothing happened. Just curious, what did you expect to happen?

Concerning the thermostat, one name is _Dummy_Thermostat Ankleide_Raumtemperaturregler_ABB700CA89FB_

Again, sorry for being so all over the place.

**Comment by ruebox** [comment]
If you do not mind, I would check the log file. 

The dataPoint is the Id for different functionalities of the device. Could be that I am using the wrong onces. Difficult as I do not have these things integrated at my home.

Thanks for your support

**Comment by BastianZim** [comment]
No problem, do you mean the normal log file or getAll.xml? Is there a special section you need because I changed quite a lot and it's rather long now, then I would quickly reinstall Openhab.

Ahh, ok, that makes sense.

No worries, thanks for developing everything.

**Comment by ruebox** [comment]
Openhab.log and getAll.xml would be great ... if you do not mind.

**Comment by BastianZim** [comment]
No problem, let me setup it up again and then I'll send it to you.

**Comment by lassem** [comment]
Responding to @Lucurus request in issue #7.
I tested the thermostat integration.
Got a Thing setup and I am able to input a new temperature and the value is reflected in the physical devices' display.
I would be surprised if it didn't work.

![image](https://user-images.githubusercontent.com/116084/37571562-9a3d1da2-2afe-11e8-89c1-b0cff942037c.png)

**Comment by lassem** [comment]
Also (as you would expect) the BasicUI does not reflect changes when setting the temperature on the physical device.

**Comment by ruebox** [comment]
I this are good new thanks a lot for testing. Feedback from physical device to openhab is the next step when thermostat and switches are working.

Dimmer can also be done ... let's see how much time will be left ;-)

**Comment by BastianZim** [comment]
Ok, that's good to hear. So the general setup is correct then,  I'll just have to recheck my configuration then after I set it up again and will report back.

**Comment by lassem** [comment]
I tried setting up a configuration for a switch, but couldn't get it to work. Also, most of my switches are missing. Probably due to the fact that most of them are dimmer switches.

**Comment by BastianZim** [comment]
Oh yes, dimmer would be great!

**Comment by BastianZim** [comment]
The only switch working right now for me is 8/8. Do you have problems with those as well?

**Comment by lassem** [comment]
Sorry, user error... The switch is working, but I had configured the wrong one.
So, the only one working for me is a 4/4

**Comment by BastianZim** [comment]
Ok, great to hear, so B+J is not distinguishing between the number of switches.

**Comment by ruebox** [comment]
Hi! 
Thanks a lot for testing. Thus, you got the switches and thermostat properly running or do you still have problems? Please just let me know ;-)

@Lucurus: There are no distinct 8/8 or 4/4 devices. For 8/8, 8 switches will be generated.

**Comment by BastianZim** [comment]
Yes, sorry, I was too quick and mixed up dimmers and switches.

**Comment by ruebox** [comment]
great good to know ... dimmer will be the next ... uploaded a new version under issue #7 
Please just give it a try

**Comment by lassem** [comment]
Rollerblind actuator 1/1 seems to be missing, I have some. F.ex serial# ABB700CE7395
Rollerblind actuator 2/2 seems to be missing as well. ABB700C6DA5F
Switch actuator 1/1 ABB700C6E2BA missing
Switch actuator 2/2 ABB700C72E96 missing

Let me know if you need anything or want me to test.

**Comment by ruebox** [comment]
Please check release channel #10 for an updated jar.

**Comment by Lucurus** [comment]
Hey, thanks for the continued development, I have installed the newest version of a fresh OpenHAB setup using Raspbian on a Raspberry Pi 3 and attached the logs and files below.

[events.log](https://github.com/ruebox/openhab2-addons/files/1842875/events.log)

[openhab.log](https://github.com/ruebox/openhab2-addons/files/1842876/openhab.log)

[getAll.xml.zip](https://github.com/ruebox/openhab2-addons/files/1842880/getAll.xml.zip)


Couple things that I noticed:

- During the first setup when I have to configure the bridge, I have to refresh the website in order to see it, not sure if it's because of the addon or OpenHAB
- I have Auto-Approve and Simple Mode switched on, yet no Thing is added. The Things are only added when I go to "Things" and click on "activate" on any channel, even if it is already activated. Again not sure if it's because of the addon or OpenHAB.
- No thermostats are displayed
- Only 8/8 switches are discovered but don't work.
- 4/4 dimmers work, thanks for that!


One more question, would you like me to open new issues for those problems in the future, or should I continue to post them here?

**Comment by ruebox** [comment]
Hi @Lucurus 
Thanks for sending the getAllxml. Please find my responses below:
* In the log, the bridge goes to online, but the state is not properly refreshed on the webui. Seems to be a openhab issue
* I am running oh 2.2. release. With auto-approve and simple mode all items are directly added and are available under control and things. -> OK for me
* Your "Raumtemperaturregler" has the deviceID=1004 and was not yet part of the implementation (only deviceId=9004" is supported) -> will be fixed with next update
* The 8/8 switch is implemented as by sstadlberger. Commands look OK. Do you configure the switches in a special manner? Please see #9 where I provide a short explanation how to filter out the xmpp commands when executing the B+J webUI. Please cross-check if idp0000 is used to switch on/off the device. Thanks.
* Great
* Perfect

I think it is not necessary to write separate issues. I will fix the temperature.

**Comment by ruebox** [comment]
fixed with 88c0ff78a709f3489a01f026670f1311c1bf463c
Switch actuator 1/1 (900C) -> ch0003
Switch actuator 2/2 (9010) -> ch0006 ch0007
