### ISSUE TITLE
Add Items manually with .items-config-file

### ISSUE THREAD

**Issue by hendrik-d** [ruebox/openhab2-addons#45]
Hello! Is it possible to add freeathome items manually by adding them in the .items config file? I want to use the freeathome binding with the homekit binding and therefore need to add the items manually. Until now i found no example for the free@home-binding specific data between the { ... }.

**Comment by ruebox** [comment]
If you add the things via discovery things are added to the registry. If simple mode for item linking is enabled in Configuration -> system then corresponding items are generated that are visible in habpanel and all other uis.
Hope this helps.

**Comment by hendrik-d** [comment]
Thanks for your answer! I know, but for the homekit binding I have to add some additional declaration for each item in the .items config file, therefore i need to add them manually. Is that possible?

**Comment by ruebox** [comment]
I think it should be feasible. However this would be a generic feature of openhab and not the binding itself.
1. Configure your items in a .items file
1. Switch of simple link mode: System configuration -> Simple linking
1. Discover your B+J stuff. If simple mode is off, only things, but not linked items are generated.
1. Configure a thing: Now you should be able to select the channels of a thing and connect it to the items.

When simple mode is deactivated, you can reconfigure all thing -> channel -> item linkages.
Yes give it a try. Hope this helps. Otherwise just let me know
